# Generated by Django 5.2.8 on 2025-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
